services:
  comfy3d:
    image: michaelgold/comfy3d:v0.3.66-cuda12.8
    container_name: comfy3d-studio
    shm_size: 16gb
    ports:
      - "8188:8188"
    volumes:
      - ./output:/app/comfy/output:cached
      - ./workflows:/app/comfy/user/default/workflows:cached
      - ./input:/app/comfy/input:cached
      - comfyui-nodes:/app/comfy/custom_nodes
      - ./models:/app/comfy/models
      - comfyui-manager:/app/comfy/user/default/ComfyUI-Manager
      - comfyui-u2net:/root/.u2net
      - .:/workspace
    gpus: all


volumes:
  comfyui-manager:
  comfyui-u2net:
  comfyui-nodes:

